spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/traveldb}
    username: ${DB_USERNAME:traveluser}
    password: ${DB_PASSWORD:travelpass123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080

  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    com.travelplatform: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
